<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="49467" started-at="2017-10-29T23:05:19Z" finished-at="2017-10-29T23:06:09Z">
    <groups>
    </groups>
    <test name="LoginTest" duration-ms="49467" started-at="2017-10-29T23:05:19Z" finished-at="2017-10-29T23:06:09Z">
      <class name="com.office.RTD_MYRIDE.tests.LoginTest">
        <test-method status="PASS" signature="beforesuite()[pri:0, instance:com.office.RTD_MYRIDE.tests.LoginTest@7dc7cbad]" name="beforesuite" is-config="true" duration-ms="0" started-at="2017-10-29T19:05:19Z" finished-at="2017-10-29T19:05:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforesuite -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.office.RTD_MYRIDE.tests.LoginTest@7dc7cbad]" name="beforeMethod" is-config="true" duration-ms="5386" started-at="2017-10-29T19:05:20Z" finished-at="2017-10-29T19:05:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="testloginsuccessful(java.lang.String, java.lang.String)[pri:0, instance:com.office.RTD_MYRIDE.tests.LoginTest@7dc7cbad]" name="testloginsuccessful" duration-ms="1027" started-at="2017-10-29T19:05:25Z" data-provider="dataprovider" finished-at="2017-10-29T19:05:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[shinnymol@outlook.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[@Anjali0505]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testloginsuccessful -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.office.RTD_MYRIDE.tests.LoginTest@7dc7cbad]" name="afterMethod" is-config="true" duration-ms="902" started-at="2017-10-29T19:05:26Z" finished-at="2017-10-29T19:05:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.office.RTD_MYRIDE.tests.LoginTest@7dc7cbad]" name="beforeMethod" is-config="true" duration-ms="4581" started-at="2017-10-29T19:05:27Z" finished-at="2017-10-29T19:05:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="testloginsuccessful(java.lang.String, java.lang.String)[pri:0, instance:com.office.RTD_MYRIDE.tests.LoginTest@7dc7cbad]" name="testloginsuccessful" duration-ms="15451" started-at="2017-10-29T19:05:32Z" data-provider="dataprovider" finished-at="2017-10-29T19:05:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[jsr@yahoo.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[welcome]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[login is failed for jsr@yahoo.com expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: login is failed for jsr@yahoo.com expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.office.RTD_MYRIDE.tests.LoginTest.testloginsuccessful(LoginTest.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testloginsuccessful -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.office.RTD_MYRIDE.tests.LoginTest@7dc7cbad]" name="afterMethod" is-config="true" duration-ms="810" started-at="2017-10-29T19:05:47Z" finished-at="2017-10-29T19:05:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.office.RTD_MYRIDE.tests.LoginTest@7dc7cbad]" name="beforeMethod" is-config="true" duration-ms="4575" started-at="2017-10-29T19:05:48Z" finished-at="2017-10-29T19:05:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="testloginsuccessful(java.lang.String, java.lang.String)[pri:0, instance:com.office.RTD_MYRIDE.tests.LoginTest@7dc7cbad]" name="testloginsuccessful" duration-ms="15495" started-at="2017-10-29T19:05:52Z" data-provider="dataprovider" finished-at="2017-10-29T19:06:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[abc@yahoo.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[ram]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[login is failed for abc@yahoo.com expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: login is failed for abc@yahoo.com expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.office.RTD_MYRIDE.tests.LoginTest.testloginsuccessful(LoginTest.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testloginsuccessful -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.office.RTD_MYRIDE.tests.LoginTest@7dc7cbad]" name="afterMethod" is-config="true" duration-ms="820" started-at="2017-10-29T19:06:08Z" finished-at="2017-10-29T19:06:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- com.office.RTD_MYRIDE.tests.LoginTest -->
    </test> <!-- LoginTest -->
  </suite> <!-- Suite -->
</testng-results>
